import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from '@/components/Header'
import { classNames } from '@/utils/class-names'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Pocket Quran',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={classNames(
          inter.className,
          'relative container mx-auto max-w-[500px]',
        )}
      >
        <Header />
        <main className="min-h-[70vh]">{children}</main>
      </body>
    </html>
  )
}
